name: CI

on:
  push:
    branches:
    - master
    - staging
    - trying
  pull_request:
    branches:
    - master

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
    - name: Succeed
      run: true
